version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    # volumes:
    #   - .:/app # Раскомментируйте для локальной разработки

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    command: ["python", "-m", "bot.bot"]
    # volumes:
    #   - .:/app # Раскомментируйте для локальной разработки

# Пример секции для PostgreSQL, если вы захотите запустить его в Docker
#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env.db # Создайте этот файл с POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
#    ports:
#      - "5432:5432"

# volumes:
#   postgres_data: