FROM python:3.10.13-slim-bullseye

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir alembic asyncpg psycopg2-binary python-dotenv

# Копируем необходимые файлы
COPY alembic.ini .
COPY alembic ./alembic
COPY server ./server
COPY config.py .

# Убедитесь, что env переменные доступны
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=Al02082003
ENV POSTGRES_DB=malterdb

CMD ["alembic", "upgrade", "head"]