FROM python:3.10.13-slim-bullseye

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir --retries 5 --timeout 60 -r requirements.txt

# Копируем необходимые файлы
COPY alembic.ini .
COPY alembic ./alembic
COPY server ./server
COPY config.py .

# Переменные окружения передаются через docker-compose

CMD ["alembic", "upgrade", "head"]