"""add_relationship_system_to_user_profile

Revision ID: 052f342e12ad
Revises: 794ea7500a0c
Create Date: 2025-07-29 21:43:58.464771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052f342e12ad'
down_revision: Union[str, Sequence[str], None] = '794ea7500a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_level', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('relationship_score', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('level_unlocked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('has_subscription', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('has_subscription')
        batch_op.drop_column('level_unlocked_at')
        batch_op.drop_column('relationship_score')
        batch_op.drop_column('relationship_level')

    # ### end Alembic commands ###
