"""Add fact_embedding to long_term_memories

Revision ID: 1342d46e5a35
Revises: ada10413cd76
Create Date: 2025-07-31 15:29:07.646123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1342d46e5a35'
down_revision: Union[str, Sequence[str], None] = 'ada10413cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.drop_column('fact_embedding')

    # ### end Alembic commands ###
