"""add last_processed_payment_charge_id to user_profiles

Revision ID: 44fa2e2662e1
Revises: bfa8e93d72e0
Create Date: 2025-09-24 10:58:31.906379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fa2e2662e1'
down_revision: Union[str, Sequence[str], None] = 'bfa8e93d72e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_processed_payment_charge_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('last_processed_payment_charge_id')

    # ### end Alembic commands ###
