"""update_user_profile_remove_fields_add_gender

Revision ID: 492b46cd5c26
Revises: 052f342e12ad
Create Date: 2025-07-31 15:01:32.089769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492b46cd5c26'
down_revision: Union[str, Sequence[str], None] = '052f342e12ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.drop_column('place')
        batch_op.drop_column('hobby')
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hobby', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
