"""fix_update_user_profile_remove_fields_add_gender

Revision ID: ada10413cd76
Revises: 492b46cd5c26
Create Date: 2025-07-31 15:07:27.438969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada10413cd76'
down_revision: Union[str, Sequence[str], None] = '492b46cd5c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
