"""fix_add_subscription_fields_to_user_profiles

Revision ID: bfa8e93d72e0
Revises: ef01ebfc2d92
Create Date: 2025-07-31 19:12:03.811436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa8e93d72e0'
down_revision: Union[str, Sequence[str], None] = 'ef01ebfc2d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('subscription_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('daily_message_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_message_date', sa.Date(), nullable=True))
        batch_op.drop_column('has_subscription')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_subscription', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('last_message_date')
        batch_op.drop_column('daily_message_count')
        batch_op.drop_column('subscription_expires')
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
