"""Delete fact_embedding to long_term_memories

Revision ID: ef01ebfc2d92
Revises: 1342d46e5a35
Create Date: 2025-07-31 16:24:35.233472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef01ebfc2d92'
down_revision: Union[str, Sequence[str], None] = '1342d46e5a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.drop_column('fact_embedding')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
